import * as THREE from 'three';
import { ABILITIES, ITEMS, OBJECTIVES, RARITIES } from './definitions';
import { AudioEngine } from './audio';
import { storage } from './libs/persistence';
import { ElderheartBoss, Enemy, FXSystem, Hero, LootDrop, Projectile, type AttackSpec, type EnemyKind } from './entities';
import { UI, type InventoryEntry, type InventorySnapshot } from './ui';
import { BRIDGE, COURT, HAVEN, World, type Interactable } from './world';
import { clamp, xpToNext } from './utils';

interface SaveData{version:1;level:number;xp:number;coins:number;shards:number;inventory:InventoryEntry[];equipped:Record<string,string>;enhancements:Record<string,number>;objective:number;campsCleared:string[];opened:string[];lore:string[];bossDefeated:boolean;position:{x:number;y:number;z:number}}
type State='title'|'playing'|'dialog'|'paused'|'boss-intro'|'dead';
interface CampDef{id:string;x:number;z:number;story:boolean;enemies:{kind:EnemyKind;dx:number;dz:number;elite?:boolean}[]}
interface Hazard{pos:THREE.Vector3;t:number;damage:number;radius:number;hit:boolean}
const SAVE_KEY='maples_save_v1';
const CAMPS:CampDef[]=[
  {id:'camp-west',x:-44,z:24,story:true,enemies:[{kind:'sprigling',dx:-2,dz:1},{kind:'sprigling',dx:2,dz:-1},{kind:'mossfang',dx:0,dz:3}]},
  {id:'camp-deep',x:-72,z:-10,story:true,enemies:[{kind:'thornshell',dx:0,dz:0},{kind:'sprigling',dx:3,dz:2},{kind:'sprigling',dx:-3,dz:1}]},
  {id:'camp-south',x:-34,z:61,story:true,enemies:[{kind:'mossfang',dx:-2,dz:0},{kind:'mossfang',dx:2,dz:1},{kind:'wispling',dx:0,dz:-3}]},
  {id:'northreach',x:76,z:-125,story:false,enemies:[{kind:'mossfang',dx:-3,dz:1,elite:true},{kind:'wispling',dx:2,dz:-2},{kind:'thornshell',dx:4,dz:3}]},
  {id:'hollow',x:79,z:-156,story:false,enemies:[{kind:'wispling',dx:-3,dz:1},{kind:'wispling',dx:3,dz:-1,elite:true}]},
];
const CHESTS:Record<string,{coins:number;shards:number;items:string[]}>= {haven:{coins:28,shards:2,items:['potion','potion']},tower:{coins:45,shards:4,items:['moonfang']},hollow:{coins:36,shards:5,items:['storm_charm']},waterfall:{coins:34,shards:3,items:['sentinel_mail']}};
const DROP_POOLS:Record<EnemyKind,string[]>={sprigling:['oakbrand','maple_charm'],thornshell:['thorn_guard','sentinel_mail'],wispling:['wisp_charm','storm_charm'],mossfang:['oakbrand','warden_mail']};

export class Game{
  readonly renderer:THREE.WebGLRenderer;readonly scene=new THREE.Scene();readonly camera=new THREE.PerspectiveCamera(58,1,.1,420);readonly world:World;readonly ui:UI;readonly audio=new AudioEngine();readonly hero=new Hero();readonly fx=new FXSystem();readonly boss=new ElderheartBoss();
  private state:State='title';private enemies:Enemy[]=[];private enemyCamp=new WeakMap<Enemy,string>();private projectiles:Projectile[]=[];private loot:LootDrop[]=[];private hazards:Hazard[]=[];private keys=new Set<string>();private cooldowns={shockwave:0,nova:0,dodge:0,potion:0};
  private level=1;private xp=0;private coins=0;private shards=0;private inventory:InventoryEntry[]=[{id:'potion',count:2},{id:'rusty_blade',count:1},{id:'traveler_mail',count:1},{id:'timber_shield',count:1},{id:'maple_charm',count:1}];private enhancements:Record<string,number>={};private objective=0;private campsCleared=new Set<string>();private opened=new Set<string>();private lore=new Set<string>();private bossDefeated=false;
  private camYaw=.55;private camPitch=.3;private camDist=7;private trauma=0;private camLook=new THREE.Vector3();private drag=false;private dragMoved=false;private pointerStart={x:0,y:0,t:0};private last=performance.now();private elapsed=0;private hitstop=0;private autosave=0;private currentZone='';private interactable:Interactable|null=null;private target:Enemy|null=null;private targetMarker:THREE.Mesh;private bossIntro=0;private deathTimer=0;private bossDeathRewarded=false;private frameAccum=0;private frameCount=0;private renderScale=1;
  constructor(canvas:HTMLCanvasElement,root:HTMLElement){this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.04;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.ui=new UI(root);this.world=new World(this.scene,this.ui.mobile?'mobile':'desktop');this.scene.add(this.fx.group,this.hero.group,this.boss.group);this.hero.position.set(3,this.world.heightAt(3,7),7);this.boss.group.position.set(COURT.x,this.world.heightAt(COURT.x,COURT.z),COURT.z);this.targetMarker=new THREE.Mesh(new THREE.OctahedronGeometry(.16,0),new THREE.MeshBasicMaterial({color:0xffd080,transparent:true,opacity:.92,depthWrite:false}));this.targetMarker.visible=false;this.scene.add(this.targetMarker);this.ui.bindActions({light:()=>this.light(),heavyStart:()=>this.heavyStart(),heavyRelease:()=>this.heavyRelease(),dodge:()=>this.dodge(),ability:id=>this.ability(id),potion:()=>this.potion(),interact:()=>this.interact(),toggleInventory:()=>this.toggleInventory(),closeInventory:()=>this.closeInventory(),equip:id=>this.equip(id),use:id=>this.useItem(id),enhance:id=>this.enhance(id),sortInventory:()=>this.sortInventory(),resume:()=>this.resume(),save:()=>void this.save(true),toggleMute:()=>this.audio.toggleMute(),newGame:()=>void this.newGame(),startNew:()=>void this.newGame(),continueGame:()=>void this.continueGame()});this.setupInput(canvas);this.resize()}
  async start(){this.spawnWorld();const save=await this.load();this.ui.showTitle(!!save);this.last=performance.now();requestAnimationFrame(this.loop)}
  resize(){const r=this.renderer.domElement.getBoundingClientRect(),w=Math.max(1,r.width||innerWidth),h=Math.max(1,r.height||innerHeight),max=this.ui.mobile?1.5:2;this.renderer.setPixelRatio(Math.min(devicePixelRatio,max)*this.renderScale);this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
  private loop=(now:number)=>{requestAnimationFrame(this.loop);let dt=Math.min(.05,(now-this.last)/1000);this.last=now;this.elapsed+=dt;if(this.state==='title'){this.updateAttract(dt);this.world.update(dt,this.hero.position);this.fx.update(dt);this.audio.update(dt);this.renderer.render(this.scene,this.camera);return}if(this.state==='paused'||this.ui.isInventoryOpen()){this.world.update(dt,this.hero.position);this.fx.update(dt*.2);this.audio.update(dt);this.renderer.render(this.scene,this.camera);return}const sim=this.hitstop>0?dt*.06:dt;this.hitstop=Math.max(0,this.hitstop-dt);if(this.state==='boss-intro')this.updateBossIntro(dt);else if(this.state==='dead')this.updateDeath(dt);else if(this.state==='playing')this.updateGameplay(sim);this.updateCamera(dt);this.world.update(dt,this.hero.position);this.fx.update(dt);const right=new THREE.Vector3().setFromMatrixColumn(this.camera.matrixWorld,0);this.audio.setListener(this.hero.position.x,this.hero.position.z,right.x,right.z);this.audio.update(dt);this.renderer.render(this.scene,this.camera);this.adaptive(dt)};
  private begin(){void this.audio.unlock();this.state='playing';this.ui.hideTitle();this.ui.setPlaying(true);this.ui.fadeToBlack(false);this.ui.zoneTitle(this.world.zoneAt(this.hero.position.x,this.hero.position.z));this.syncUI(true)}
  private async continueGame(){const s=await this.load();if(s)this.applySave(s);this.begin()}
  private async newGame(){await storage.removeItem(SAVE_KEY);this.level=1;this.xp=0;this.coins=0;this.shards=0;this.inventory=[{id:'potion',count:2},{id:'rusty_blade',count:1},{id:'traveler_mail',count:1},{id:'timber_shield',count:1},{id:'maple_charm',count:1}];this.enhancements={};this.hero.equipment={weapon:'rusty_blade',armor:'traveler_mail',shield:'timber_shield',amulet:'maple_charm'};this.hero.enhancement=this.enhancements;this.hero.setEquipment(this.hero.equipment);this.hero.recalc(1);this.objective=0;this.campsCleared.clear();this.opened.clear();this.lore.clear();this.bossDefeated=false;this.bossDeathRewarded=false;this.hero.respawn(new THREE.Vector3(3,this.world.heightAt(3,7),7));this.resetEnemies();this.boss.active=false;this.boss.alive=true;this.boss.state='dormant';this.boss.hp=this.boss.maxHp;this.boss.group.visible=true;this.world.setBossArena(false);this.ui.closeInventory();this.begin();await this.save(false)}
  private spawnWorld(){this.resetEnemies();this.boss.group.position.set(COURT.x,this.world.heightAt(COURT.x,COURT.z),COURT.z)}
  private resetEnemies(){for(const e of this.enemies)this.scene.remove(e.group);this.enemies=[];for(const c of CAMPS){if(c.story&&this.campsCleared.has(c.id))continue;for(const s of c.enemies){const p=new THREE.Vector3(c.x+s.dx,this.world.heightAt(c.x+s.dx,c.z+s.dz),c.z+s.dz),e=new Enemy(s.kind,p,!!s.elite);this.enemies.push(e);this.enemyCamp.set(e,c.id);this.scene.add(e.group)}}}
  private updateGameplay(dt:number){for(const k of Object.keys(this.cooldowns) as (keyof typeof this.cooldowns)[])this.cooldowns[k]=Math.max(0,this.cooldowns[k]-dt);this.updateTarget();const move=this.moveVector(),sprint=this.keys.has('ShiftLeft')||this.keys.has('ShiftRight'),ty=this.target&&this.target.position.distanceTo(this.hero.position)<6?Math.atan2(this.target.position.x-this.hero.position.x,this.target.position.z-this.hero.position.z):undefined;this.hero.update(dt,move,sprint,(x,z)=>this.world.heightAt(x,z),{attack:s=>this.resolveHeroAttack(s),step:p=>this.audio.sfx('step',p.x,p.z,this.world.footstepAt(p.x,p.z)),ability:k=>this.resolveAbility(k)},this.hero.isBusy?ty:undefined);this.world.resolveCollisions(this.hero.position,this.hero.radius);
    let attackers=this.enemies.filter(e=>e.alive&&e.state==='windup').length;for(let i=this.enemies.length-1;i>=0;i--){const e=this.enemies[i];if(!e.alive&&e.state==='dead'&&e.stateTime>1.2){this.handleEnemyDeath(e);this.scene.remove(e.group);this.enemies.splice(i,1);continue}const allow=attackers<2||e.state==='windup'||e.state==='recover';const prev=e.state;e.update(dt,this.hero,(x,z)=>this.world.heightAt(x,z),{attack:(en,d)=>this.enemyMelee(en,d),shoot:(en,d)=>this.enemyShoot(en,d),telegraph:(en,r,d)=>this.fx.telegraph(en.position,r,d),died:()=>{}},allow);this.world.resolveCollisions(e.position,e.radius);if(prev!=='windup'&&e.state==='windup')attackers++}this.updateBoss(dt);this.updateProjectiles(dt);this.updateHazards(dt);this.updateLoot(dt);this.findInteractable();this.updateZone();this.checkStory();this.autosave+=dt;if(this.autosave>12){this.autosave=0;void this.save(false)}this.syncUI()}
  private moveVector(){let x=0,z=0;if(this.keys.has('KeyW'))z+=1;if(this.keys.has('KeyS'))z-=1;if(this.keys.has('KeyA'))x-=1;if(this.keys.has('KeyD'))x+=1;if(this.ui.joystick.active){x+=this.ui.joystick.x;z+=this.ui.joystick.y}const v=new THREE.Vector3();if(!x&&!z)return v;const len=Math.hypot(x,z);x/=len;z/=len;const f=new THREE.Vector3(Math.sin(this.camYaw),0,Math.cos(this.camYaw)),r=new THREE.Vector3(f.z,0,-f.x);return v.addScaledVector(r,x).addScaledVector(f,z).normalize()}
  private updateTarget(){let best:Enemy|null=null,score=Infinity;const camF=new THREE.Vector3();this.camera.getWorldDirection(camF);camF.y=0;camF.normalize();for(const e of this.enemies){if(!e.alive)continue;const d=e.position.clone().sub(this.hero.position),dist=d.length();if(dist>10)continue;d.y=0;d.normalize();const angle=1-camF.dot(d),s=dist+angle*5;if(s<score){score=s;best=e}}this.target=best;this.targetMarker.visible=!!best;if(best){this.targetMarker.position.copy(best.position).add(new THREE.Vector3(0,best.radius*2+1.15,0));this.targetMarker.rotation.y=this.elapsed*2.5}}
  private light(){if(this.state==='playing'&&this.hero.startLight())this.audio.sfx('swing',this.hero.position.x,this.hero.position.z,Math.floor(Math.random()*3))}private heavyStart(){if(this.state==='playing'&&this.hero.startHeavy())this.audio.sfx('heavy',this.hero.position.x,this.hero.position.z)}private heavyRelease(){this.hero.releaseHeavy()}private dodge(){if(this.state!=='playing'||this.cooldowns.dodge>0)return;if(this.hero.dodge(this.moveVector())){this.cooldowns.dodge=ABILITIES.dodge.cooldown;this.audio.sfx('dodge',this.hero.position.x,this.hero.position.z)}}
  private ability(id:'shockwave'|'nova'){if(this.state!=='playing'||this.cooldowns[id]>0)return;if(id==='nova'&&this.level<3){this.ui.toast('Emberleaf Nova unlocks at level 3.','warn');return}if(this.hero.useAbility(id)){this.cooldowns[id]=ABILITIES[id].cooldown;this.audio.sfx(id==='shockwave'?'shockwave':'nova',this.hero.position.x,this.hero.position.z)}}
  private resolveHeroAttack(s:AttackSpec){const forward=this.hero.forward;let hit=false;for(const e of this.enemies){if(!e.alive)continue;const to=e.position.clone().sub(this.hero.position),dist=to.length();if(dist>s.range+e.radius)continue;to.y=0;to.normalize();if(forward.dot(to)<Math.cos(s.arc/2))continue;const crit=Math.random()<this.hero.crit,dmg=this.hero.baseAtk*s.multiplier*(crit?1.8:1),result=e.takeDamage(dmg,s.poise,forward,this.hero.position);hit=true;this.floatWorld(e.position.clone().add(new THREE.Vector3(0,1.4,0)),result.blocked?'BLOCKED':String(result.dealt),result.blocked?'blocked':crit?'crit':'damage');this.fx.burst(e.position.clone().add(new THREE.Vector3(0,.8,0)),result.blocked?0xc3d0db:0xffb05a,result.blocked?6:12,s.heavy?4:2.8);this.audio.sfx('impact',e.position.x,e.position.z,s.heavy?2:0);if(result.killed)this.grantXP(e.xp);if(s.heavy||s.finisher){this.hitstop=Math.max(this.hitstop,.055);this.trauma=Math.min(1,this.trauma+.25)}}if(this.boss.active&&this.boss.alive){const to=this.boss.position.clone().sub(this.hero.position),dist=to.length();to.y=0;to.normalize();if(dist<s.range+this.boss.radius&&forward.dot(to)>Math.cos(s.arc/2)){const crit=Math.random()<this.hero.crit,res=this.boss.takeDamage(this.hero.baseAtk*s.multiplier*(crit?1.8:1),s.poise,forward);hit=true;this.floatWorld(this.boss.position.clone().add(new THREE.Vector3(0,4.5,0)),String(res.dealt),crit?'crit':'damage');this.fx.burst(this.boss.position.clone().add(new THREE.Vector3(0,3,0)),0xffa344,16,3.4);this.hitstop=Math.max(this.hitstop,s.heavy?.065:.025)}}if(hit&&navigator.vibrate&&s.heavy)navigator.vibrate(18)}
  private resolveAbility(id:'shockwave'|'nova'){const radius=id==='shockwave'?4.2:6.1,mult=id==='shockwave'?2.1:2.85;this.fx.ring(this.hero.position,radius===4.2?0xd7b36a:0xff814d,radius);for(const e of this.enemies){const d=e.position.distanceTo(this.hero.position);if(e.alive&&d<radius+e.radius){const dir=e.position.clone().sub(this.hero.position).setY(0).normalize(),res=e.takeDamage(this.hero.baseAtk*mult,id==='shockwave'?38:25,dir,this.hero.position);this.floatWorld(e.position.clone().add(new THREE.Vector3(0,1.4,0)),String(res.dealt),id==='nova'?'burn':'damage');if(res.killed)this.grantXP(e.xp)}}if(this.boss.active&&this.boss.alive&&this.boss.position.distanceTo(this.hero.position)<radius+this.boss.radius){const res=this.boss.takeDamage(this.hero.baseAtk*mult,40,new THREE.Vector3());this.floatWorld(this.boss.position.clone().add(new THREE.Vector3(0,4,0)),String(res.dealt),'crit')}this.trauma=Math.min(1,this.trauma+.32);this.hitstop=.045}
  private enemyMelee(e:Enemy,damage:number){const d=this.hero.position.clone().sub(e.position),dist=d.length();if(dist>e.def.range+this.hero.radius+1)return;const dir=d.setY(0).normalize(),dealt=this.hero.takeDamage(damage,dir);if(dealt)this.hurtPlayer(dealt)}private enemyShoot(e:Enemy,damage:number){const from=e.position.clone().add(new THREE.Vector3(0,1.1,0)),dir=this.hero.position.clone().add(new THREE.Vector3(0,.8,0)).sub(from).normalize(),p=new Projectile(from,dir.multiplyScalar(8.5),damage);this.projectiles.push(p);this.scene.add(p.mesh)}
  private hurtPlayer(dealt:number){this.ui.damagePulse();this.floatWorld(this.hero.position.clone().add(new THREE.Vector3(0,1.9,0)),`-${dealt}`,'player');this.audio.sfx('hurt',this.hero.position.x,this.hero.position.z);this.trauma=Math.min(1,this.trauma+.34);if(this.hero.dead)this.startDeath()}
  private updateProjectiles(dt:number){for(let i=this.projectiles.length-1;i>=0;i--){const p=this.projectiles[i];p.update(dt);if(!p.dead&&p.pos.distanceTo(this.hero.position)<p.radius+this.hero.radius){const dir=p.vel.clone().setY(0).normalize(),d=this.hero.takeDamage(p.damage,dir);if(d)this.hurtPlayer(d);p.dead=true}if(p.dead){this.scene.remove(p.mesh);this.projectiles.splice(i,1)}}}
  private updateBoss(dt:number){if(!this.boss.active||!this.boss.alive){if(this.boss.active&&!this.boss.alive&&!this.bossDeathRewarded&&this.boss.state==='dead'&&this.boss.stateTime>.9)this.finishBoss();return}this.boss.update(dt,this.hero,{telegraph:(kind,pos,r,d)=>{this.fx.telegraph(pos,r,d,kind==='nova'?0xff7f43:0xff534a)},resolve:kind=>this.resolveBossAttack(kind)});this.ui.setBoss('Elderheart Colossus',this.boss.hp/this.boss.maxHp,true)}
  private resolveBossAttack(kind:string){const center=this.boss.position;if(kind==='slam'){if(this.hero.position.distanceTo(center)<4.2){const d=this.hero.takeDamage(26,this.hero.position.clone().sub(center).setY(0).normalize());if(d)this.hurtPlayer(d)}this.fx.ring(center,0xff7d48,4.5);this.trauma=.7}else if(kind==='sweep'){if(this.hero.position.distanceTo(center)<5.1){const d=this.hero.takeDamage(20,this.hero.position.clone().sub(center).setY(0).normalize());if(d)this.hurtPlayer(d)}this.fx.ring(center,0xff934f,5)}else if(kind==='roots'){for(let i=0;i<3;i++){const p=this.hero.position.clone();p.x+=(Math.random()-.5)*4;p.z+=(Math.random()-.5)*4;this.hazards.push({pos:p,t:.8+i*.28,damage:14,radius:1.35,hit:false});this.fx.telegraph(p,1.35,.8+i*.28)}}else if(kind==='summon'){for(let i=0;i<2;i++){const a=i*Math.PI+Math.random(),p=center.clone().add(new THREE.Vector3(Math.cos(a)*5,0,Math.sin(a)*5));p.y=this.world.heightAt(p.x,p.z);const e=new Enemy('sprigling',p,this.boss.phase===2&&Math.random()>.5);this.enemies.push(e);this.scene.add(e.group)}this.ui.toast('The Elderheart calls saplings from the soil.','warn')}else if(kind==='nova'){if(this.hero.position.distanceTo(center)<7.4){const d=this.hero.takeDamage(34,this.hero.position.clone().sub(center).setY(0).normalize());if(d)this.hurtPlayer(d)}this.fx.ring(center,0xff6d3f,7.4);this.trauma=.9}this.audio.sfx(kind==='nova'?'boss':'shockwave',center.x,center.z)}
  private updateHazards(dt:number){for(let i=this.hazards.length-1;i>=0;i--){const h=this.hazards[i];h.t-=dt;if(h.t<=0&&!h.hit){h.hit=true;this.fx.burst(h.pos.clone().add(new THREE.Vector3(0,.2,0)),0xb87345,18,5);if(this.hero.position.distanceTo(h.pos)<h.radius+this.hero.radius){const d=this.hero.takeDamage(h.damage,this.hero.position.clone().sub(h.pos).setY(0).normalize());if(d)this.hurtPlayer(d)}}if(h.t<-.35)this.hazards.splice(i,1)}}
  private beginBoss(){if(this.bossDefeated||this.boss.active)return;this.state='boss-intro';this.bossIntro=0;this.ui.showLetterbox(true);this.world.setBossArena(true);this.audio.setMode('boss');this.audio.sfx('boss',COURT.x,COURT.z);this.boss.awaken(new THREE.Vector3(COURT.x,this.world.heightAt(COURT.x,COURT.z),COURT.z));this.ui.setBoss('Elderheart Colossus',1,true)}private updateBossIntro(dt:number){this.bossIntro+=dt;const t=clamp(this.bossIntro/3.2,0,1),a=.8+t*1.5;this.camera.position.set(COURT.x+Math.cos(a)*(12-3*t),14+2*t,COURT.z+Math.sin(a)*(12-3*t));this.camera.lookAt(this.boss.position.clone().add(new THREE.Vector3(0,3,0)));if(this.bossIntro>3.2){this.state='playing';this.ui.showLetterbox(false);this.ui.toast('ELDERHEART COLOSSUS','epic')}}
  private finishBoss(){this.bossDeathRewarded=true;this.bossDefeated=true;this.boss.active=false;this.objective=4;this.ui.hideBoss();this.world.setBossArena(false);this.audio.setMode('explore');this.grantXP(420);this.coins+=120;this.shards+=12;this.addItem('heartcleaver',1);this.addItem('elderheart_amber',1);this.fx.burst(this.boss.position.clone().add(new THREE.Vector3(0,3,0)),0xffc45c,70,6);this.ui.toast('The Elderheart is quiet. Heartcleaver recovered.','epic');void this.save(false)}
  private checkStory(){const storyCleared=[...this.campsCleared].filter(id=>CAMPS.find(c=>c.id===id)?.story).length;if(this.objective===1&&storyCleared>=3){this.objective=2;this.ui.toast('The Maplewild is quiet. Cross the Old Bridge.','good')}if(this.objective===2&&this.hero.position.distanceTo(COURT)<26&&!this.bossDefeated){this.objective=3;this.beginBoss()}if(this.objective===0&&this.hero.position.distanceTo(HAVEN)>30)this.ui.toast('Warden Bram waits beneath the Great Maple.','warn')}
  private handleEnemyDeath(e:Enemy){const camp=this.enemyCamp.get(e);if(camp&&!this.campsCleared.has(camp)){const any=this.enemies.some(x=>x!==e&&x.alive&&this.enemyCamp.get(x)===camp);if(!any){this.campsCleared.add(camp);this.ui.toast(CAMPS.find(c=>c.id===camp)?.story?'Corrupted camp cleared.':'Hunting ground cleared.','good')}}const base=e.kind==='sprigling'?3:e.kind==='thornshell'?7:6;this.spawnLoot(e.position,base*(e.elite?3:1),e.elite?3:Math.random()<.18?1:0,Math.random()<(e.elite?.7:.24)?DROP_POOLS[e.kind][Math.floor(Math.random()*DROP_POOLS[e.kind].length)]:null)}
  private spawnLoot(pos:THREE.Vector3,coins:number,shards:number,itemId:string|null){const make=(kind:'coin'|'shard'|'item',opts:any)=>{const l=new LootDrop(kind,pos.clone().add(new THREE.Vector3((Math.random()-.5)*.6,.8,(Math.random()-.5)*.6)),opts);this.loot.push(l);this.scene.add(l.group)};make('coin',{amount:coins});if(shards)make('shard',{amount:shards});if(itemId)make('item',{itemId,rarity:ITEMS[itemId].rarity})}
  private updateLoot(dt:number){for(let i=this.loot.length-1;i>=0;i--){const l=this.loot[i];l.update(dt,this.world.heightAt(l.group.position.x,l.group.position.z),this.hero.position);if(l.group.position.distanceTo(this.hero.position)<.85&&l.age>.25){if(l.kind==='coin'){this.coins+=l.amount;this.audio.sfx('coin')}else if(l.kind==='shard'){this.shards+=l.amount;this.audio.sfx('pickup')}else{this.addItem(l.itemId,1);this.audio.sfx('pickup');this.ui.toast(`${ITEMS[l.itemId].name} · ${RARITIES[ITEMS[l.itemId].rarity].name}`,ITEMS[l.itemId].rarity==='epic'?'epic':'good')}l.dead=true}if(l.dead){this.scene.remove(l.group);this.loot.splice(i,1)}}}
  private grantXP(v:number){this.xp+=v;while(this.xp>=xpToNext(this.level)){this.xp-=xpToNext(this.level);this.level++;this.hero.recalc(this.level);this.hero.hp=this.hero.maxHp;this.audio.sfx('level');this.fx.ring(this.hero.position,0xffd06c,3);this.ui.toast(`Level ${this.level}${this.level===3?' · Emberleaf Nova unlocked':''}`,'epic')}}
  private potion(){if(this.state!=='playing'||this.cooldowns.potion>0)return;const e=this.inventory.find(i=>i.id==='potion');if(!e?.count||this.hero.hp>=this.hero.maxHp)return;const healed=this.hero.heal(45);e.count--;if(!e.count)this.inventory=this.inventory.filter(i=>i!==e);this.cooldowns.potion=1;this.audio.sfx('potion');this.fx.burst(this.hero.position.clone().add(new THREE.Vector3(0,1,0)),0x6fe997,18,2);this.floatWorld(this.hero.position.clone().add(new THREE.Vector3(0,2,0)),`+${healed}`,'heal');this.syncUI(true)}
  private findInteractable(){this.interactable=this.world.nearestInteractable(this.hero.position.x,this.hero.position.z);this.ui.setPrompt(this.interactable?.label??null)}private interact(){if(this.state!=='playing'||!this.interactable)return;const it=this.interactable;if(it.kind==='npc')this.talkBram();else if(it.kind==='chest')this.openChest(it);else if(it.kind==='lore'){if(!this.lore.has(it.id)){this.lore.add(it.id);this.shards++;}this.ui.showDialog('Weathered Memory',it.data??'The stone has forgotten its words.');}else if(it.kind==='sign')this.ui.showDialog('Waystone',it.data??'');else if(it.kind==='shrine'){if(this.bossDefeated){this.ui.showDialog('Court Shrine','The amber is warm. The guardian rests, but its trial can be remembered.');}else this.ui.showDialog('Court Shrine','A sleeping pulse answers from beneath the stone.')}}
  private talkBram(){if(this.objective===0){this.state='dialog';this.dialogSequence('Warden Bram',['Rowan. The Great Maple is dimming, and the wild has begun to answer the silence.','Clear the three corrupted camps west of the haven. Then take the old bridge to the Sunken Court.','Do not mistake the Elderheart for a beast. It was our guardian before something wounded its will.'],()=>{this.objective=1;this.state='playing';this.syncUI(true)})}else if(this.objective<4)this.ui.showDialog('Warden Bram',this.objective===1?'Three camps. Break their corruption before you cross the river.':'The old bridge still holds. The Court lies beyond it.');else this.ui.showDialog('Warden Bram','The maple breathes easier. Keep Heartcleaver close; old wounds have a way of speaking again.')}
  private dialogSequence(name:string,lines:string[],done:()=>void){let i=0;const next=()=>{if(i>=lines.length){this.ui.closeDialog();done();return}this.ui.showDialog(name,lines[i++],next)};next()}
  private openChest(it:Interactable){if(this.opened.has(it.id)){this.ui.toast('The cache is empty.');return}this.opened.add(it.id);const key=it.data??'',c=CHESTS[key]??{coins:25,shards:2,items:[]};this.coins+=c.coins;this.shards+=c.shards;for(const id of c.items)this.addItem(id,1);this.audio.sfx('pickup');this.fx.burst(new THREE.Vector3(it.x,this.world.heightAt(it.x,it.z)+.6,it.z),0xffc56c,25,3.4);this.ui.toast(`Cache opened · ${c.coins} coin · ${c.shards} shard${c.shards===1?'':'s'}`,'good');void this.save(false)}
  private toggleInventory(){if(this.state==='title'||this.state==='boss-intro'||this.state==='dead')return;if(this.ui.isInventoryOpen())this.closeInventory();else{this.ui.openInventory(this.inventorySnapshot());this.ui.setPause(false)}}private closeInventory(){this.ui.closeInventory();if(this.state==='paused')this.state='playing'}private equip(id:string){const item=ITEMS[id];if(!item||!['weapon','armor','shield','amulet'].includes(item.type))return;(this.hero.equipment as Record<string,string>)[item.type]=id;this.hero.setEquipment(this.hero.equipment);this.hero.enhancement=this.enhancements;this.hero.recalc(this.level);this.ui.setInventory(this.inventorySnapshot());this.audio.sfx('ui')}
  private useItem(id:string){if(id==='potion')this.potion()}private enhance(id:string){const item=ITEMS[id];if(!item||!['weapon','armor','shield','amulet'].includes(item.type))return;const n=this.enhancements[id]??0;if(n>=3)return;const cost=10*(n+1);if(this.shards<cost){this.ui.toast(`Need ${cost} Amber Shards.`,'warn');return}this.shards-=cost;this.enhancements[id]=n+1;this.hero.enhancement=this.enhancements;this.hero.recalc(this.level);this.audio.sfx('pickup');this.ui.toast(`${item.name} enhanced to +${n+1}.`,'good');this.ui.setInventory(this.inventorySnapshot())}private sortInventory(){const rank={epic:3,rare:2,uncommon:1,common:0};this.inventory.sort((a,b)=>rank[ITEMS[b.id].rarity]-rank[ITEMS[a.id].rarity]||ITEMS[a.id].name.localeCompare(ITEMS[b.id].name));this.ui.setInventory(this.inventorySnapshot())}
  private addItem(id:string,count=1){const e=this.inventory.find(x=>x.id===id);if(e)e.count+=count;else this.inventory.push({id,count})}private inventorySnapshot():InventorySnapshot{return{items:this.inventory.map(i=>({...i})),equipped:{...this.hero.equipment},shards:this.shards,coins:this.coins,potions:this.inventory.find(i=>i.id==='potion')?.count??0,enhancements:{...this.enhancements}}}
  private updateZone(){const z=this.world.zoneAt(this.hero.position.x,this.hero.position.z);if(z!==this.currentZone){this.currentZone=z;this.ui.zoneTitle(z);if(z==='Sunken Court'&&this.boss.active)this.audio.setMode('boss');else if(this.enemies.some(e=>e.alive&&e.position.distanceTo(this.hero.position)<10))this.audio.setMode('combat');else this.audio.setMode('explore')}}
  private updateCamera(dt:number){if(this.state==='boss-intro')return;const target=this.hero.position.clone().add(new THREE.Vector3(0,1.3,0));this.camLook.lerp(target,1-Math.exp(-10*dt));const cp=Math.cos(this.camPitch),desired=new THREE.Vector3(this.camLook.x-Math.sin(this.camYaw)*cp*this.camDist,this.camLook.y+Math.sin(this.camPitch)*this.camDist+1.2,this.camLook.z-Math.cos(this.camYaw)*cp*this.camDist);let dist=this.camDist;for(let i=1;i<=10;i++){const t=i/10,p=this.camLook.clone().lerp(desired,t),ground=this.world.heightAt(p.x,p.z);if(p.y<ground+.35){dist=this.camDist*(i-1)/10;break}}const pos=new THREE.Vector3(this.camLook.x-Math.sin(this.camYaw)*cp*dist,this.camLook.y+Math.sin(this.camPitch)*dist+1.2,this.camLook.z-Math.cos(this.camYaw)*cp*dist);this.trauma=Math.max(0,this.trauma-dt*1.9);if(this.trauma>0){const a=this.trauma*this.trauma;pos.x+=Math.sin(this.elapsed*71)*a*.18;pos.y+=Math.sin(this.elapsed*93)*a*.12}this.camera.position.lerp(pos,1-Math.exp(-13*dt));this.camera.lookAt(this.camLook)}private updateAttract(dt:number){this.camYaw+=dt*.055;const focus=new THREE.Vector3(0,3,0),dist=17;this.camera.position.set(Math.sin(this.camYaw)*dist,9,Math.cos(this.camYaw)*dist);this.camera.lookAt(focus)}
  private startDeath(){if(this.state==='dead')return;this.state='dead';this.deathTimer=0;this.audio.setMode('explore');this.ui.showDeath(true);this.ui.fadeToBlack(false)}private updateDeath(dt:number){this.deathTimer+=dt;if(this.deathTimer>2.2&&this.deathTimer-dt<=2.2)this.ui.fadeToBlack(true);if(this.deathTimer>2.8){this.coins=Math.max(0,Math.floor(this.coins*.9));this.hero.respawn(new THREE.Vector3(3,this.world.heightAt(3,7),7));this.state='playing';this.ui.showDeath(false);this.ui.fadeToBlack(false);this.ui.toast('You awaken beneath the Great Maple.','warn');this.resetEnemies();this.syncUI(true)}}
  private resume(){if(this.state==='paused'){this.state='playing';this.ui.setPause(false)}else if(this.state==='playing'){this.state='paused';this.ui.setPause(true)}}
  private setupInput(canvas:HTMLCanvasElement){addEventListener('keydown',e=>{this.keys.add(e.code);if(e.repeat)return;if(e.code==='KeyJ')this.light();if(e.code==='KeyK')this.heavyStart();if(e.code==='Space'){e.preventDefault();this.dodge()}if(e.code==='KeyQ')this.ability('shockwave');if(e.code==='KeyE')this.ability('nova');if(e.code==='KeyR')this.potion();if(e.code==='KeyF')this.interact();if(e.code==='KeyI'||e.code==='KeyB')this.toggleInventory();if(e.code==='Escape'){if(this.ui.isInventoryOpen())this.closeInventory();else this.resume()}if(e.code==='KeyM')this.audio.toggleMute()});addEventListener('keyup',e=>{this.keys.delete(e.code);if(e.code==='KeyK')this.heavyRelease()});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(this.ui.mobile||this.state!=='playing')return;this.drag=true;this.dragMoved=false;this.pointerStart={x:e.clientX,y:e.clientY,t:performance.now()};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const dx=e.movementX,dy=e.movementY;if(Math.abs(dx)+Math.abs(dy)>2)this.dragMoved=true;this.camYaw-=dx*.006;this.camPitch=clamp(this.camPitch+dy*.004,-.05,.9)});canvas.addEventListener('pointerup',e=>{if(!this.drag)return;this.drag=false;if(!this.dragMoved&&performance.now()-this.pointerStart.t<260&&e.button===0)this.light();if(!this.dragMoved&&e.button===2){this.heavyStart();setTimeout(()=>this.heavyRelease(),240)}});canvas.addEventListener('wheel',e=>{this.camDist=clamp(this.camDist+Math.sign(e.deltaY)*.6,4.3,10.5)},{passive:true});let touchId=-1,lastX=0,lastY=0;canvas.addEventListener('pointerdown',e=>{if(!this.ui.mobile||e.pointerType!=='touch')return;touchId=e.pointerId;lastX=e.clientX;lastY=e.clientY});canvas.addEventListener('pointermove',e=>{if(!this.ui.mobile||e.pointerId!==touchId)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;this.camYaw-=dx*.009;this.camPitch=clamp(this.camPitch+dy*.007,-.05,.92)});canvas.addEventListener('pointerup',e=>{if(e.pointerId===touchId)touchId=-1});addEventListener('visibilitychange',()=>{if(document.hidden&&this.state==='playing'){this.state='paused';this.ui.setPause(true)}})}
  private syncUI(force=false){if(this.state==='title'&&!force)return;this.ui.setHP(this.hero.hp,this.hero.maxHp);this.ui.setXP(this.level,this.xp);this.ui.setCurrency(this.coins,this.shards);const progress=this.objective===1?`${[...this.campsCleared].filter(id=>CAMPS.find(c=>c.id===id)?.story).length} / 3` : '';this.ui.setObjective(this.objective,progress);this.ui.setCooldown('shockwave',this.cooldowns.shockwave/ABILITIES.shockwave.cooldown);this.ui.setCooldown('nova',this.cooldowns.nova/ABILITIES.nova.cooldown,this.level<3);this.ui.setCooldown('dodge',this.cooldowns.dodge/ABILITIES.dodge.cooldown);this.ui.setInventory(this.inventorySnapshot())}
  private floatWorld(pos:THREE.Vector3,text:string,kind:string){const p=pos.clone().project(this.camera);if(p.z<-1||p.z>1)return;this.ui.floatText((p.x*.5+.5)*innerWidth,(-p.y*.5+.5)*innerHeight,text,kind)}
  private async load(){try{const raw=await storage.getItem(SAVE_KEY);return raw?JSON.parse(raw) as SaveData:null}catch{return null}}private applySave(s:SaveData){if(s.version!==1)return;this.level=Math.max(1,s.level);this.xp=Math.max(0,s.xp);this.coins=Math.max(0,s.coins);this.shards=Math.max(0,s.shards);this.inventory=s.inventory?.length?s.inventory:[{id:'potion',count:2}];this.enhancements=s.enhancements??{};this.hero.equipment={...this.hero.equipment,...s.equipped};this.hero.enhancement=this.enhancements;this.hero.setEquipment(this.hero.equipment);this.hero.recalc(this.level);this.objective=clamp(s.objective??0,0,OBJECTIVES.length-1);if(this.objective===3&&!s.bossDefeated)this.objective=2;this.campsCleared=new Set(s.campsCleared??[]);this.opened=new Set(s.opened??[]);this.lore=new Set(s.lore??[]);this.bossDefeated=!!s.bossDefeated;if(s.position&&Number.isFinite(s.position.x)){this.hero.position.set(s.position.x,s.position.y,s.position.z);this.world.resolveCollisions(this.hero.position,this.hero.radius)}this.hero.hp=this.hero.maxHp;this.resetEnemies();if(this.bossDefeated){this.boss.group.visible=false;this.boss.active=false;this.boss.alive=false}}
  private async save(showToast:boolean){const s:SaveData={version:1,level:this.level,xp:this.xp,coins:this.coins,shards:this.shards,inventory:this.inventory.map(i=>({...i})),equipped:{...this.hero.equipment},enhancements:{...this.enhancements},objective:this.objective,campsCleared:[...this.campsCleared],opened:[...this.opened],lore:[...this.lore],bossDefeated:this.bossDefeated,position:{x:this.hero.position.x,y:this.hero.position.y,z:this.hero.position.z}};try{await storage.setItem(SAVE_KEY,JSON.stringify(s));if(showToast)this.ui.toast('Journey saved.','good')}catch{if(showToast)this.ui.toast('Save failed in this browser.','warn')}}
  private adaptive(dt:number){this.frameAccum+=dt;this.frameCount++;if(this.frameAccum<3)return;const fps=this.frameCount/this.frameAccum;if(fps<42&&this.renderScale>.72){this.renderScale=Math.max(.72,this.renderScale-.12);this.resize()}else if(fps>58&&this.renderScale<1){this.renderScale=Math.min(1,this.renderScale+.06);this.resize()}this.frameAccum=0;this.frameCount=0}
}
