import { ABILITIES, ITEMS, OBJECTIVES, RARITIES, type ItemDef } from './definitions';
import { clamp, formatNumber, xpToNext } from './utils';

export interface InventoryEntry { id:string; count:number; enhance?:number; }
export interface InventorySnapshot { items:InventoryEntry[]; equipped:Record<string,string>; shards:number; coins:number; potions:number; enhancements:Record<string,number>; selected?:string|null; }
export interface UIActions {
  light():void; heavyStart():void; heavyRelease():void; dodge():void; ability(id:'shockwave'|'nova'):void; potion():void; interact():void; toggleInventory():void; closeInventory():void; equip(id:string):void; use(id:string):void; enhance(id:string):void; sortInventory():void; resume():void; save():void; toggleMute():boolean; newGame():void; startNew():void; continueGame():void;
}

export class UI {
  readonly root:HTMLElement; readonly mobile:boolean; joystick={x:0,y:0,active:false};
  actions:UIActions|null=null; private hpFill!:HTMLElement;private hpText!:HTMLElement;private xpFill!:HTMLElement;private levelBadge!:HTMLElement;private coin!:HTMLElement;private shard!:HTMLElement;private obj!:HTMLElement;private boss!:HTMLElement;private bossName!:HTMLElement;private bossFill!:HTMLElement;private prompt!:HTMLElement;private promptText!:HTMLElement;private toasts!:HTMLElement;private dialog!:HTMLElement;private zone!:HTMLElement;private inventory!:HTMLElement;private detail!:HTMLElement;private grid!:HTMLElement;private fade!:HTMLElement;private damage!:HTMLElement;private death!:HTMLElement;private title!:HTMLElement;private pause!:HTMLElement;private touch!:HTMLElement;private joyBase!:HTMLElement;private joyKnob!:HTMLElement;private floatLayer!:HTMLElement;private abilityEls=new Map<string,HTMLElement>();private inventoryState:InventorySnapshot|null=null;private selected:string|null=null;private titleContinue!:HTMLButtonElement;private objectiveIndex=0;
  constructor(root:HTMLElement){this.root=root;this.mobile=matchMedia('(pointer: coarse)').matches||innerWidth<820;this.build();this.bindBase();}

  bindActions(actions:UIActions){this.actions=actions;this.bindActionButtons();}
  setPlaying(v:boolean){document.body.classList.toggle('playing',v);document.getElementById('hud')?.classList.toggle('hidden',!v);this.touch.classList.toggle('hidden',!v||!this.mobile);}
  showTitle(hasSave:boolean){this.title.classList.remove('hidden');this.titleContinue.style.display=hasSave?'inline-flex':'none';this.fade.classList.remove('black');}
  hideTitle(){this.title.classList.add('leaving');setTimeout(()=>this.title.classList.add('hidden'),520);}
  setHP(hp:number,max:number){const f=clamp(hp/max,0,1);this.hpFill.style.transform=`scaleX(${f})`;this.hpText.textContent=`${Math.ceil(hp)} / ${max}`;}
  setXP(level:number,xp:number){this.levelBadge.textContent=`${level}`;this.xpFill.style.transform=`scaleX(${clamp(xp/xpToNext(level),0,1)})`;}
  setCurrency(coins:number,shards:number){this.coin.textContent=formatNumber(coins);this.shard.textContent=formatNumber(shards);}
  setObjective(index:number,extra=''){this.objectiveIndex=index;this.obj.textContent=OBJECTIVES[index]+(extra?` ${extra}`:'');}
  setBoss(name:string,f:number,show=true){this.boss.classList.toggle('hidden',!show);this.bossName.textContent=name;this.bossFill.style.transform=`scaleX(${clamp(f,0,1)})`;}
  hideBoss(){this.boss.classList.add('hidden');}
  setCooldown(id:string,frac:number,locked=false){const el=this.abilityEls.get(id);if(!el)return;el.style.setProperty('--cooldown',`${clamp(frac,0,1)*360}deg`);el.classList.toggle('locked',locked);const l=el.querySelector('.lock-label');if(l)l.textContent=locked?'Lv 3':'';}
  setPrompt(label:string|null){this.prompt.classList.toggle('hidden',!label);this.promptText.textContent=label??'';document.getElementById('btn-interact')?.classList.toggle('hidden',!label);}
  toast(text:string,kind=''){const d=document.createElement('div');d.className=`toast ${kind}`;d.textContent=text;this.toasts.appendChild(d);setTimeout(()=>d.classList.add('show'),20);setTimeout(()=>{d.classList.remove('show');setTimeout(()=>d.remove(),350)},2600);}
  zoneTitle(name:string){this.zone.textContent=name;this.zone.classList.remove('show');void this.zone.offsetWidth;this.zone.classList.add('show');}
  damagePulse(){this.damage.classList.remove('pulse');void this.damage.offsetWidth;this.damage.classList.add('pulse');if(navigator.vibrate)navigator.vibrate(20);}
  fadeToBlack(v:boolean){this.fade.classList.toggle('black',v);}
  showDeath(v:boolean){this.death.classList.toggle('show',v);}
  setPause(v:boolean){this.pause.classList.toggle('hidden',!v);}
  showLetterbox(v:boolean){document.body.classList.toggle('letterbox-on',v);}

  floatText(x:number,y:number,text:string,kind='damage'){const d=document.createElement('div');d.className=`float-text ${kind}`;d.textContent=text;d.style.left=`${x}px`;d.style.top=`${y}px`;this.floatLayer.appendChild(d);setTimeout(()=>d.remove(),950);}
  showDialog(name:string,text:string,onAdvance?:()=>void){this.dialog.classList.remove('hidden');this.dialog.innerHTML=`<div class="dialog-name">${name}</div><div class="dialog-text">${text}</div><div class="dialog-next">Tap / F <span>›</span></div>`;const advance=()=>{this.dialog.classList.add('hidden');this.dialog.onclick=null;onAdvance?.()};this.dialog.onclick=advance;}
  closeDialog(){this.dialog.classList.add('hidden');}

  setInventory(snapshot:InventorySnapshot){this.inventoryState=snapshot;this.selected=this.selected&&snapshot.items.some(i=>i.id===this.selected)?this.selected:null;this.renderInventory();}
  openInventory(snapshot:InventorySnapshot){this.inventoryState=snapshot;this.inventory.classList.remove('hidden');this.renderInventory();}
  closeInventory(){this.inventory.classList.add('hidden');this.selected=null;}
  isInventoryOpen(){return !this.inventory.classList.contains('hidden');}

  private renderInventory(){const s=this.inventoryState;if(!s)return;const rarityOrder={common:0,uncommon:1,rare:2,epic:3};const items=[...s.items].sort((a,b)=>rarityOrder[ITEMS[b.id].rarity]-rarityOrder[ITEMS[a.id].rarity]);this.grid.innerHTML=items.map(e=>{const it=ITEMS[e.id];const enh=s.enhancements[e.id]??0;return `<button class="item-slot rarity-${it.rarity} ${this.selected===e.id?'selected':''}" data-item="${e.id}" style="--rarity:${RARITIES[it.rarity].color}"><span class="item-glyph">${this.glyph(it)}</span>${e.count>1?`<b>${e.count}</b>`:''}${enh?`<em>+${enh}</em>`:''}<i></i></button>`}).join('')+Array.from({length:Math.max(0,24-items.length)},()=>'<div class="item-slot empty"></div>').join('');
    const equip=document.getElementById('equip-row')!;equip.innerHTML=['weapon','armor','shield','amulet'].map(type=>{const id=s.equipped[type],it=ITEMS[id];return `<button class="equip-slot rarity-${it?.rarity??'common'}" data-item="${id??''}"><small>${type}</small><span>${it?this.glyph(it):'·'}</span><strong>${it?.name??'Empty'}</strong></button>`}).join('');
    (document.getElementById('inv-shards')!).textContent=`◆ ${s.shards}`;(document.getElementById('inv-coins')!).textContent=`● ${s.coins}`;this.renderDetail();
  }
  private renderDetail(){const s=this.inventoryState,id=this.selected;if(!s||!id){this.detail.innerHTML='<div class="detail-empty"><span>✦</span><p>Select an item to inspect its story and stats.</p></div>';return;}const it=ITEMS[id],enh=s.enhancements[id]??0;const stats=it.stats??{};const type=it.type;const equippedId=['weapon','armor','shield','amulet'].includes(type)?s.equipped[type]:null;const equipped=equippedId?ITEMS[equippedId]:null;const statRows=Object.entries(stats).map(([k,v])=>{const eq=equipped?.stats?.[k as keyof typeof equipped.stats]??0;const display=k==='crit'||k==='speed'?`${Math.round((v as number)*100)}%`:`${Math.round((v as number)*(1+enh*.1))}`;const delta=(v as number)*(1+enh*.1)-(eq as number);return `<div class="stat"><span>${k.toUpperCase()}</span><b>${display}</b>${equippedId&&equippedId!==id?`<em class="${delta>=0?'up':'down'}">${delta>=0?'+':''}${k==='crit'||k==='speed'?Math.round(delta*100)+'%':Math.round(delta)}</em>`:''}</div>`}).join('');const canEquip=['weapon','armor','shield','amulet'].includes(type),canEnh=canEquip&&enh<3,enhCost=10*(enh+1);this.detail.innerHTML=`<div class="detail-rarity" style="color:${RARITIES[it.rarity].color}">${RARITIES[it.rarity].name} ${it.type}</div><div class="detail-title">${it.name}${enh?` +${enh}`:''}</div><div class="detail-icon" style="--rarity:${RARITIES[it.rarity].color}">${this.glyph(it)}</div><p>${it.description}</p><div class="stats">${statRows||'<div class="stat"><span>Utility item</span></div>'}</div><div class="detail-actions">${canEquip?`<button data-action="equip" data-id="${id}">${equippedId===id?'Equipped':'Equip'}</button>`:''}${type==='consumable'?`<button data-action="use" data-id="${id}">Use</button>`:''}${canEnh?`<button data-action="enhance" data-id="${id}" ${s.shards<enhCost?'disabled':''}>Enhance · ${enhCost} ◆</button>`:''}</div>`;}
  private glyph(it:ItemDef){switch(it.type){case'weapon':return'⚔';case'armor':return'♜';case'shield':return'⬟';case'amulet':return'◇';case'consumable':return'⚗';case'material':return'◆';}}

  private build(){this.root.innerHTML=`
    <div id="vignette"></div><div id="damage-flash"></div><div id="fade-layer" class="black"></div><div id="letterbox-top" class="letterbox"></div><div id="letterbox-bottom" class="letterbox"></div><div id="float-layer"></div>
    <div id="hud" class="hidden">
      <section id="player-plate"><div class="crest">M</div><div class="player-bars"><div class="hp"><div id="hp-fill"></div><span id="hp-text">100 / 100</span></div><div class="xp"><div id="xp-fill"></div></div></div><div id="level-badge">1</div></section>
      <div id="currency"><span class="coin-dot">●</span><b id="coin-count">0</b><span class="shard-dot">◆</span><b id="shard-count">0</b></div>
      <section id="objective-card"><small>PATH OF THE KEEPER</small><div id="objective-text">${OBJECTIVES[0]}</div></section>
      <section id="boss-bar" class="hidden"><small>AWAKENED GUARDIAN</small><div id="boss-name">Elderheart Colossus</div><div class="boss-track"><div id="boss-hp-fill"></div></div></section>
      <div id="ability-bar">${this.abilitySlot('light','J','⚔','Light')}${this.abilitySlot('heavy','K','⬇','Heavy')}${this.abilitySlot('shockwave','Q','✹','Shockwave')}${this.abilitySlot('nova','E','✦','Nova',true)}${this.abilitySlot('dodge','SPACE','↻','Dodge')}${this.abilitySlot('potion','R','⚗','Tonic')}</div>
      <div id="interact-prompt" class="hidden"><kbd>F</kbd><span id="interact-label"></span></div>
      <div id="toasts"></div><div id="zone-title"></div>
      <button id="hud-bag" class="hud-round" aria-label="Inventory">▦</button><button id="hud-sound" class="hud-round" aria-label="Mute">♪</button>
    </div>
    <div id="dialog" class="hidden"></div>
    <div id="touch-ui" class="hidden"><div id="joystick-zone"><div id="joy-base"><div id="joy-knob"></div></div></div><div id="action-cluster"><button id="btn-attack" class="touch-action primary">⚔<span>Attack</span></button><button id="btn-heavy" class="touch-action">⬇<span>Heavy</span></button><button id="btn-dodge" class="touch-action">↻<span>Dodge</span></button><button id="btn-q" class="touch-action ability">✹<span>Q</span></button><button id="btn-e" class="touch-action ability">✦<span>E</span></button><button id="btn-potion" class="touch-action small">⚗</button><button id="btn-bag" class="touch-action small">▦</button><button id="btn-interact" class="touch-action interact hidden">◎<span>Use</span></button></div></div>
    <section id="inventory" class="menu-panel hidden"><header><div><small>KEEPER'S SATCHEL</small><h2>Inventory</h2></div><div class="inv-money"><span id="inv-coins">● 0</span><span id="inv-shards">◆ 0</span></div><button id="inv-sort">Sort</button><button id="inv-close">×</button></header><div id="equip-row"></div><div class="inventory-body"><div id="item-grid"></div><aside id="item-detail"></aside></div></section>
    <section id="pause-menu" class="menu-panel compact hidden"><small>MAPLES</small><h2>Journey Paused</h2><button id="pause-resume">Return to the wild</button><button id="pause-save">Save journey</button><button id="pause-mute">Toggle sound</button><button id="pause-new" class="danger">Begin a new journey</button></section>
    <section id="title-screen"><div class="title-scrim"></div><div class="title-copy"><div class="leaf-mark">◆</div><h1>MAPLES</h1><p class="title-kicker">THE SUNKEN COURT</p><p class="title-desc">A hand-built-feeling fantasy region. A sleeping guardian. One road through a living wild.</p><div class="title-actions"><button id="continue-btn">Continue Journey</button><button id="new-btn">New Journey</button></div><div class="title-controls">${this.mobile?'Move with the left stick · Drag the world to turn the camera · Fight with the right controls':'WASD move · Mouse drag camera · J/LMB light · K heavy · Space dodge · Q/E abilities · F interact · I inventory'}</div></div><footer>THREE.JS ACTION-RPG VERTICAL SLICE</footer></section>
    <section id="death-screen"><small>THE WILD REMEMBERS</small><h2>You Have Fallen</h2><p>The Great Maple calls you home.</p></section>`;
    this.hpFill=this.q('#hp-fill');this.hpText=this.q('#hp-text');this.xpFill=this.q('#xp-fill');this.levelBadge=this.q('#level-badge');this.coin=this.q('#coin-count');this.shard=this.q('#shard-count');this.obj=this.q('#objective-text');this.boss=this.q('#boss-bar');this.bossName=this.q('#boss-name');this.bossFill=this.q('#boss-hp-fill');this.prompt=this.q('#interact-prompt');this.promptText=this.q('#interact-label');this.toasts=this.q('#toasts');this.dialog=this.q('#dialog');this.zone=this.q('#zone-title');this.inventory=this.q('#inventory');this.detail=this.q('#item-detail');this.grid=this.q('#item-grid');this.fade=this.q('#fade-layer');this.damage=this.q('#damage-flash');this.death=this.q('#death-screen');this.title=this.q('#title-screen');this.pause=this.q('#pause-menu');this.touch=this.q('#touch-ui');this.joyBase=this.q('#joy-base');this.joyKnob=this.q('#joy-knob');this.floatLayer=this.q('#float-layer');this.titleContinue=this.q('#continue-btn') as HTMLButtonElement;for(const id of['light','heavy','shockwave','nova','dodge','potion'])this.abilityEls.set(id,this.q(`[data-ability="${id}"]`));}
  private abilitySlot(id:string,key:string,icon:string,name:string,locked=false){return `<div class="ability-slot ${locked?'locked':''}" data-ability="${id}" style="--cooldown:0deg"><div class="ability-cooldown"></div><span class="ability-icon">${icon}</span><kbd>${key}</kbd><small>${name}</small><em class="lock-label">${locked?'Lv 3':''}</em></div>`;}
  private q(sel:string){return this.root.querySelector(sel) as HTMLElement;}

  private bindBase(){
    this.q('#inv-close').onclick=()=>this.actions?.closeInventory();this.q('#inv-sort').onclick=()=>this.actions?.sortInventory();this.q('#hud-bag').onclick=()=>this.actions?.toggleInventory();this.q('#hud-sound').onclick=()=>{const m=this.actions?.toggleMute();this.toast(m?'Sound muted':'Sound restored')};this.q('#pause-resume').onclick=()=>this.actions?.resume();this.q('#pause-save').onclick=()=>this.actions?.save();this.q('#pause-mute').onclick=()=>this.actions?.toggleMute();this.q('#pause-new').onclick=()=>this.actions?.newGame();this.q('#new-btn').onclick=()=>this.actions?.startNew();this.titleContinue.onclick=()=>this.actions?.continueGame();
    this.grid.onclick=(e)=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-item]');if(!b)return;this.selected=b.dataset.item??null;this.renderInventory();};this.q('#equip-row').onclick=(e)=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-item]');if(!b?.dataset.item)return;this.selected=b.dataset.item;this.renderInventory();};this.detail.onclick=(e)=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-action]');if(!b)return;const id=b.dataset.id!;if(b.dataset.action==='equip')this.actions?.equip(id);if(b.dataset.action==='use')this.actions?.use(id);if(b.dataset.action==='enhance')this.actions?.enhance(id);};
    this.bindJoystick();
  }

  private bindActionButtons(){
    const click=(id:string,fn:()=>void)=>{const el=this.q(id);el.addEventListener('pointerdown',e=>{e.preventDefault();fn();});};click('#btn-attack',()=>this.actions?.light());click('#btn-dodge',()=>this.actions?.dodge());click('#btn-q',()=>this.actions?.ability('shockwave'));click('#btn-e',()=>this.actions?.ability('nova'));click('#btn-potion',()=>this.actions?.potion());click('#btn-bag',()=>this.actions?.toggleInventory());click('#btn-interact',()=>this.actions?.interact());const heavy=this.q('#btn-heavy');heavy.addEventListener('pointerdown',e=>{e.preventDefault();heavy.setPointerCapture(e.pointerId);this.actions?.heavyStart()});const rel=(e:PointerEvent)=>{e.preventDefault();this.actions?.heavyRelease()};heavy.addEventListener('pointerup',rel);heavy.addEventListener('pointercancel',rel);
  }
  private bindJoystick(){const zone=this.q('#joystick-zone');let pointer=-1;const update=(e:PointerEvent)=>{const r=this.joyBase.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.36,l=Math.hypot(dx,dy)||1,n=Math.min(max,l);this.joystick.x=dx/l*(n/max);this.joystick.y=-dy/l*(n/max);this.joyKnob.style.transform=`translate(${dx/l*n}px,${dy/l*n}px)`;};zone.addEventListener('pointerdown',e=>{e.preventDefault();pointer=e.pointerId;zone.setPointerCapture(pointer);this.joystick.active=true;const r=zone.getBoundingClientRect();this.joyBase.style.left=`${e.clientX-r.left}px`;this.joyBase.style.top=`${e.clientY-r.top}px`;this.joyBase.classList.add('active');update(e);});zone.addEventListener('pointermove',e=>{if(e.pointerId===pointer)update(e)});const end=(e:PointerEvent)=>{if(e.pointerId!==pointer)return;pointer=-1;this.joystick={x:0,y:0,active:false};this.joyKnob.style.transform='translate(0,0)';this.joyBase.classList.remove('active');};zone.addEventListener('pointerup',end);zone.addEventListener('pointercancel',end);}
}
